### ISSUE TITLE
Need To Reference Specific Shared Library Version

### ISSUE THREAD

**Issue by ldo** [gabdube/python-vulkan-triangle#1]
When referencing a shared library on Linux, it is important to note that the unversioned name “foo.so” comes from the development package, while a versioned name like “foo.so.1” comes from the runtime package. It is important that your Python binding has a dependency only on the runtime package, not the development package.

The [enclosed patch](https://github.com/gabdube/python-vulkan-triangle/files/394818/ldo-lib-version.txt) fixes this.

Also: death to wildcard imports!

**Comment by gabdube** [comment]
Thank you for reporting this issue. I'll fix it in an instant.

I have to agree with you about the wildcard, but with ctypes I tend to be lazy and import the whole thing.  (I'll replace the import on xmath though, it's only a few functions after all)

**Comment by ldo** [comment]
I agree long module names can be a pain if you have to type them a lot. That’s why, for ctypes in particular, I almost always write

```
import ctypes as ct
```

For example, see my [Python binding for Cairo](https://github.com/ldo/qahirah).

**Comment by gabdube** [comment]
Interesting. I will look at this.  I've commit the patch so I'll close this issue.
